name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mariamrf/py-lambda-action@v0.0.2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        LAMBDA_FUNCTION_NAME: arn:aws:lambda:us-east-1:970648805745:function:desk
        LAMBDA_LAYER_ARN: arn:aws:lambda:us-east-1:970648805745:layer:desk-layer
