name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get deps
      run: |
        curl -SL https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip > chromedriver.zip
        unzip chromedriver.zip -d bin/
        curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-29/stable-headless-chromium-amazonlinux-2017-03.zip > headless-chromium.zip
        unzip headless-chromium.zip -d bin/
        @rm headless-chromium.zip chromedriver.zip
    - uses: mariamrf/py-lambda-action@v0.0.2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        LAMBDA_FUNCTION_NAME: arn:aws:lambda:us-east-1:970648805745:function:desk
        LAMBDA_LAYER_ARN: arn:aws:lambda:us-east-1:970648805745:layer:desk-layer
